apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikito-ui
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels: { app: tikito-ui }
  template:
    metadata:
      labels: { app: tikito-ui }
    spec:
      nodeSelector: {{- toYaml .Values.ui.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.ui.tolerations | nindent 6 }}
      affinity: {{- toYaml .Values.ui.affinity | nindent 6 }}
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.containerPort }}
          env:
            # Compose used TIKITO_API_HOSTNAME: ${TIKITO_API_HOSTNAME}:${TIKITO_API_PORT}
            # Provide the full base URL the UI uses to call the API:
            - name: TIKITO_API_HOSTNAME
              value: {{ (index .Values.backend.ingress.hosts 0).host | default "api.tikito.local" | quote }}
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{- toYaml .Values.ui.resources | nindent 12 }}
