apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikito-backend
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels: { app: tikito-backend }
  template:
    metadata:
      labels: { app: tikito-backend }
    spec:
      nodeSelector: {{- toYaml .Values.backend.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.backend.tolerations | nindent 6 }}
      affinity: {{- toYaml .Values.backend.affinity | nindent 6 }}
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
          env:
            - name: SERVER_PORT
              value: {{ printf "%d" .Values.backend.port | quote }}
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: tikito-db, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: tikito-db, key: DB_PASSWORD } }
            - name: DB_HOST
              valueFrom: { secretKeyRef: { name: tikito-db, key: DB_HOST } }
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: tikito-db, key: DB_PORT } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: tikito-db, key: DB_NAME } }
            - name: FINNHUB_TOKEN
              {{- if and .Values.secrets.finnhub.enabled .Values.secrets.finnhub.token }}
              valueFrom: { secretKeyRef: { name: tikito-db, key: FINNHUB_TOKEN } }
              {{- else }}
              value: {{ .Values.backend.finnhubToken | quote }}
              {{- end }}
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{- toYaml .Values.backend.resources | nindent 12 }}
