{{- if .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tikito-ui
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ui.ingress.className | quote }}
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    {{- if .Values.ui.ingress.tls.enabled }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- end }}
spec:
  {{- if .Values.ui.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ui.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ .Values.ui.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: tikito-ui
                port:
                  number: 80
    {{- end }}
{{- end }}
