apiVersion: v1
kind: Secret
metadata:
  name: tikito-db
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
{{- if and .Values.secrets.finnhub.enabled .Values.secrets.finnhub.token }}
  FINNHUB_TOKEN: {{ .Values.secrets.finnhub.token | quote }}
{{- end }}
