apiVersion: v1
kind: Service
metadata:
  name: tikito-ui
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  type: {{ .Values.ui.service.type }}
  selector: { app: tikito-ui }
  ports:
    - name: http
      port: 80
      targetPort: http
