apiVersion: v1
kind: Service
metadata:
  name: tikito-backend
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector: { app: tikito-backend }
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
