# Override default values.yaml with custom values.yaml
provider:
  name: aws

# Use the secret external-dns that is already created
env:
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /etc/external-dns/aws-credentials
  - name: AWS_DEFAULT_REGION
    value: us-east-1
        
domainFilters:
  - mrcontainer.nl

extraVolumes:
  - name: aws-credentials
    secret:
      secretName: external-dns
      items:
        - key: credentials
          path: aws-credentials
          
extraVolumeMounts:
  - name: aws-credentials
    mountPath: /etc/external-dns
    readOnly: true