apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        revision: main
        directories:
          - path: applications/*/chart

  template:
    metadata:
      # e.g. path="core-components/metallb/chart" â†’ name="metallb-chart"
      name: '{{ base (dir .path.path) }}-{{ base .path.path }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        targetRevision: main
        path: '{{ .path.path }}'
        helm:
          # merge in ../values.yaml from each component folder
          valueFiles:
            - ../values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ base (dir .path.path) }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
