apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-manifests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        revision: main
        directories:
          - path: applications/*/manifests
  template:
    metadata:
      # e.g. path="applications/homepage/manifests" â†’ name=homepage-manifest"
      name: '{{ base (dir .path.path) }}-manifest'
    spec:
      # Using the default project for now
      project: default
      source:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ base (dir .path.path) }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true