apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        revision: main
        directories:
          - path: applications/*

  template:
    metadata:
      # each folder under applications/ becomes its own app, e.g. "homeassistant"
      name: '{{ base .path }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        targetRevision: main
        path: '{{ .path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ base .path }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
