apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-components
  namespace: argocd
spec:
  project: default

  # This is your Git repo (replace with your org/repo if different)
  source:
    repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
    targetRevision: HEAD
    path: core-components

  # Tell ArgoCD to install child Applications into the argocd namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true      # remove resources no longer defined
      selfHeal: true   # correct drift automatically
