apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-components-manifests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        revision: main
        directories:
          - path: core-components/*/manifests
  template:
    metadata:
      # e.g. path="core-components/metallb/manifests" â†’ name="metallb-manifest"
      name: '{{ base (dir .path.path) }}-manifest'
    spec:
      # Using the default project for now
      project: default
      source:
        repoURL: https://github.com/mrcontainer-tech/homelab-turing.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ base (dir .path.path) }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true