apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  secretName: harbor-tls
  dnsNames:
    - harbor.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer