apiVersion: v2
name: longhorn
description: >-
  Longhorn is a distributed block storage system for Kubernetes.
type: application
version: 1.2.3
appVersion: "v1.2.3"
home: https://longhorn.io
icon: https://raw.githubusercontent.com/longhorn/longhorn/master/logo/logo.svg
sources:
  - https://github.com/longhorn/longhorn
kubeVersion: ">= 1.19.0-0"