# Add custom helm values here
namespace: cert-manager
crds:
  enabled: true

extraEnv:
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /etc/cert-manager/aws-credentials

volumes:
  - name: aws-credentials
    secret:
      secretName: certmanager
      items:
        - key: credentials-certmanager
          path: aws-credentials

volumeMounts:
  - name: aws-credentials
    mountPath: /etc/cert-manager
