apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage
  namespace: homepage
spec:
  secretName: homepage-tls
  dnsNames:
    - homepage.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer