apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "Mr. Container Homepage"
    description: "Welcome to my self-hosted deathstar! ðŸš€"
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm 
      saturate: 50
      brightness: 50
      opacity: 50
    favicon: https://www.google.com/favicon.ico
    theme: dark # or light
    color: slate
    layout:
      Media:
        style: row
        columns: 4
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Favorite Repos:
        - Homelab-turing:
            - abbr: GH
              href: https://github.com/mrcontainer/homelab-turing
              icon: https://github.com/favicon.ico
        - Notes:
            - abbr: Notes
              href: https://github.com/scholtenmartijn/zk-vault
              icon: https://github.com/favicon.ico
    - Bookmarks:
        - Github:
            - abbr: GH
              href: https://github.com/
              icon: https://github.com/favicon.ico
        - ChatGPT:
            - abbr: ChatGPT
              href: https://chat.openai.com/
              icon: https://cdn.oaistatic.com/assets/favicon-miwirzcw.ico
        - Tweakers:
            - abbr: Tweakers
              href: https://tweakers.net/
              icon: https://tweakers.net/favicon.ico
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: https://argocd.mrcontainer.nl/
            description: GitOps ftw!
            icon: https://argocd.mrcontainer.nl/assets/favicon/favicon-32x32.png
        - Longhorn:
            href: https://longhorn.mrcontainer.nl/
            description: Longhorn is the best
            icon: http://longhorn.mrcontainer.nl/favicon.ico
    - Security:
        - Harbor:
            href: https://harbor.mrcontainer.nl/
            description: Harbor is the best
            icon: https://harbor.mrcontainer.nl/images/harbor-logo.svg
        - Kyverno:
            href: https://kyverno.mrcontainer.nl/
            description: TODO
            icon: https://kyverno.mrcontainer.nl/icon.png
    - Observability:
        - Grafana:
            href: https://grafana.mrcontainer.nl/
            description: Dashboarding
            icon: https://grafana.mrcontainer.nl/public/img/fav32.png
        - Prometheus:
            href: https://prometheus.mrcontainer.nl/
            description: TODO
            icon: https://prometheus.mrcontainer.nl/favicon.ico
  widgets.yaml: |
    - kubernetes:
        inCluster: true
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""