apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "Mr. Container Homepage"
    description: "Welcome to my self-hosted deathstar! ðŸš€"
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm 
      saturate: 50
      brightness: 50
      opacity: 50
    favicon: https://www.google.com/favicon.ico
    theme: dark # or light
    color: slate
    layout:
      Media:
        style: row
        columns: 4
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Bookmarks:
        - Github:
          href: https://github.com/
          icon: https://github.com/favicon.ico
        - ChatGPT:
          href: https://chat.openai.com/
          icon: https://cdn.oaistatic.com/assets/favicon-miwirzcw.ico
        - Tweakers:
          href: https://tweakers.net/
          icon: https://tweakers.net/favicon.ico
    - Infrastructure:
        - ArgoCD:
            href: https://argocd.mrcontainer.nl/
            description: ArgoCD is the good stuff
            icon: https://argocd.mrcontainer.nl/assets/favicon/favicon-32x32.png
        - Longhorn:
            href: https://longhorn.mrcontainer.nl/
            description: Longhorn is the best
            icon: http://longhorn.mrcontainer.nl/favicon.ico
    - Security:
        - Harbor:
            href: https://harbor.mrcontainer.nl/
            description: Harbor is the best
            icon: https://harbor.mrcontainer.nl/icon.png
        - Kyverno:
            href: https://kyverno.mrcontainer.nl/
            description: Kyverno is the best
            icon: https://kyverno.mrcontainer.nl/icon.png
    - Dashboards:
        - Grafana:
            href: http://grafana.mrcontainer.nl/
            description: Grafana is the best
            icon: https://grafana.mrcontainer.nl/icon.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""