apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "Homelab"
    description: "Welcome to my self-hosted deathstar! ðŸš€"
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm 
      saturate: 50
      brightness: 50
      opacity: 50
    favicon: https://www.google.com/favicon.ico
    theme: dark
    color: slate
    layout:
      Media:
        style: row
        columns: 4
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Favorite Repos:
        - Homelab-turing:
            - abbr: GH
              href: https://github.com/mrcontainer-tech/homelab-turing
              icon: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
        - Notes:
            - abbr: Notes
              href: https://github.com/scholtenmartijn/zk-vault
              icon: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
    - Bookmarks:
        - Github:
            - abbr: GH
              href: https://github.com/
              icon: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
        - ChatGPT:
            - abbr: ChatGPT
              href: https://chat.openai.com/
              icon: https://cdn.oaistatic.com/assets/favicon-miwirzcw.ico
        - Tweakers:
            - abbr: Tweakers
              href: https://tweakers.net/
              icon: https://tweakers.net/favicon.ico
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: https://argocd.mrcontainer.nl/
            description: GitOps ftw!
            icon: https://argocd.mrcontainer.nl/assets/favicon/favicon-32x32.png
        - Longhorn:
            href: https://longhorn.mrcontainer.nl/
            description: Longhorn is the best
            icon: http://longhorn.mrcontainer.nl/favicon.ico
    - Security:
        - Harbor:
            href: https://harbor.mrcontainer.nl/
            description: TODO
            icon: https://harbor.mrcontainer.nl/favicon.ico?v=2
        - Kyverno:
            href: https://kyverno.mrcontainer.nl/
            description: TODO
            icon: https://kyverno.mrcontainer.nl/icon.png
    - Observability:
        - Grafana:
            href: https://grafana.mrcontainer.nl/
            description: Grafana UI
            icon: https://grafana.mrcontainer.nl/public/img/fav32.png
        - Prometheus:
            href: https://prometheus.mrcontainer.nl/
            description: Prometheus UI
            icon: https://prometheus.mrcontainer.nl/favicon.svg
    - Media:
        - Jellyfin:
            href: https://jellyfin.mrcontainer.nl/
            icon: https://jellyfin.org/images/favicon.ico
            widget:
              type: jellyfin
              url: http://jellyfin.media.svc.cluster.local:8096
              key: "061e304acaeb4e99bae2b7a93c2dc11d"
        - Jellyseerr:
            href: https://jellyseerr.mrcontainer.nl/
            icon: https://jellyseerr.mrcontainer.nl/favicon-32x32.png
            widget:
              type: jellyseerr
              url: http://jellyseerr.media.svc.cluster.local:5055
              key: "MTc2MDc5OTY0NzY4OGExYTcxMDE2LWY1NjgtNGI4Mi04M2JlLTk5YzZkMmMwMWUxNg=="
        - Sonarr:
            href: https://sonarr.mrcontainer.nl/
            icon: https://sonarr.tv/img/favicon.ico
            widget:
              type: sonarr
              url: http://sonarr.media.svc.cluster.local:8989
              key: "649d8c8e141349d4832988dccec8a187"
        - Prowlarr:
            href: https://prowlarr.mrcontainer.nl/
            icon: https://prowlarr.com/img/favicon.ico
            widget:
              type: prowlarr
              url: http://prowlarr.media.svc.cluster.local:9696
              key: "fcc07f63cb964f17a63d73cf6fe92dc2"
        - Radarr:
            href: https://radarr.mrcontainer.nl/
            icon: https://radarr.mrcontainer.nl/Content/Images/Icons/favicon-32x32.png
            widget:
              type: radarr
              url: https://radarr.mrcontainer.nl
              key: "afdd1ed69e80489bb5d26cc72499f76b"
        - Bazarr:
            href: https://bazarr.mrcontainer.nl/
            icon: https://bazarr.mrcontainer.nl/images/favicon.ico
            widget:
              type: bazarr
              url: http://bazarr.media.svc.cluster.local:6767
              key: "5984156640ff4611a1d737adaa25c4dc"
        - qBittorrent:
            href: https://qb.mrcontainer.nl/
            icon: https://qb.mrcontainer.nl/images/qbittorrent32.png
            widget:
              type: qbittorrent
              url: http://qbittorrent.media.svc.cluster.local:8080
              username: "admin"
              password: "UIrzBDvyV"
  widgets.yaml: |
    - kubernetes:
        inCluster: true
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: false
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
