apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  secretName: policy-reporter-tls
  dnsNames:
    - policy-reporter.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
