---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-rwx
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 500Gi } }
  volumeName: downloads-pv