apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin
  namespace: media
spec:
  secretName: jellyfin-tls
  dnsNames:
    - jellyfin.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer