---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr-tls
  namespace: media
spec:
  secretName: jellyseerr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jellyseerr.mrcontainer.nl