---
# Claims binding explicitly to the above PVs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-rwx
  namespace: media
spec:
  storageClassName: "" 
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 900Gi } }
  volumeName: media-pv