apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr
  namespace: media
spec:
  secretName: prowlarr-tls
  dnsNames:
    - prowlarr.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer