---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  namespace: media
spec:
  secretName: radarr-tls
  dnsNames:
    - radarr.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer