apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr
  namespace: media
spec:
  secretName: sonarr-tls
  dnsNames:
    - sonarr.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer