apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: kube-prometheus-stack
spec:
  secretName: prometheus-tls
  dnsNames:
    - prometheus.mrcontainer.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer