apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: kube-prometheus-stack
spec:
  tls:
    - hosts:
        - prometheus.mrcontainer.nl
      secretName: prometheus-tls
  rules:
    - host: prometheus.mrcontainer.nl
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kube-prometheus-stack-char-prometheus
                port:
                  number: 9090