---
apiVersion: v1
kind: Service
metadata:
  name: dnscrypt-proxy
  namespace: kube-system
  labels:
    app.kubernetes.io/name: dnscrypt-proxy
    app.kubernetes.io/component: dns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dnscrypt-proxy
  ports:
    - name: dns-udp
      port: 53
      targetPort: 5053
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 5053
      protocol: TCP
